version: '3'
services:
  activemq:
    image: symptoma/activemq:latest
    ports:
      - "9020:8161"
      - "9021:61616"

  producer:
    image: kamaraj/ecs-as-cm-producer:1.0.0
    depends_on:
      - activemq
    ports:
      - "8000:8080"
      - "8001:8081"
    environment:
      - JAVA_OPTS=-XshowSettings:vm -XX:MetaspaceSize=64M -XX:MaxMetaspaceSize=128M -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError -XX:+UseStringDeduplication -XX:G1PeriodicGCSystemLoadThreshold=0.5 -XX:G1PeriodicGCInterval=210000 -XX:-G1PeriodicGCInvokesConcurrent -Dspring.jmx.enabled=false -Duser.timezone=UTC -Duser.country=US -Duser.language=en
      - APP_BROKER_URL=tcp://activemq:61616
      - APP_BROKER_USER=admin
      - APP_BROKER_PWD=admin
    healthcheck:
      test: curl --fail http://localhost:8081/actuator/health || exit 1
      interval: 60s
      retries: 5
      timeout: 10s

  consumer:
    image: kamaraj/ecs-as-cm-consumer:1.0.0
    depends_on:
      - activemq
    ports:
      - "8002:8080"
      - "8003:8081"
    environment:
      - JAVA_OPTS=-XshowSettings:vm -XX:MetaspaceSize=64M -XX:MaxMetaspaceSize=128M -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError -XX:+UseStringDeduplication -XX:G1PeriodicGCSystemLoadThreshold=0.5 -XX:G1PeriodicGCInterval=210000 -XX:-G1PeriodicGCInvokesConcurrent -Dspring.jmx.enabled=false -Duser.timezone=UTC -Duser.country=US -Duser.language=en
      - APP_BROKER_URL=tcp://activemq:61616
      - APP_BROKER_USER=admin
      - APP_BROKER_PWD=admin
    healthcheck:
      test: curl --fail http://localhost:8081/actuator/health || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
